// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfwrueizbxsywkfhiqok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmd3J1ZWl6YnhzeXdrZmhpcW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTg1MjYsImV4cCI6MjA2NDY5NDUyNn0.Idv6iw2a4Q9iOy-wMe1xw3jG0sX4mODipj8Gtx81Gsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);